name: Update RSS every 20 minutes

on:
  schedule:
    - cron: '*/20 * * * *' # تشغيل كل 20 دقيقة
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install --upgrade beautifulsoup4
          pip install --upgrade lxml

      - name: Run update script
        run: python update_rss.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add index.xml
          git commit -m 'Update RSS feed'
          git push
